### ISSUE TITLE
extract-loader 1.0.2 doesn't work with css-loader v0.28.8

### ISSUE THREAD

**Issue by rurikbor** [peerigon/extract-loader#31]
Hi guys.

css-loader v0.28.8 implements url escaping: https://github.com/webpack-contrib/css-loader/commit/8897d44

extract-loader 1.0.2 has attempt to fix incompatibility: https://github.com/peerigon/extract-loader/commit/ac3fccdd6fb0302f2a87f8ab468f7395a4c74877#diff-453648f7ddcea53f5543562ba9bf0d3d

But it doesn't work in my case since css-loader injects relative url to css-base in my case:
This leads to invalid dependency resolve:

TypeError: require(...) is not a function
    at D:\blablabla\node_modules\bootstrap\dist\css\bootstrap-theme.css:1:74
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.extractLoader (D:\blablabla\node_modules\extract-loader\lib\extractLoader.js:89:12)
 @ ./node_modules/bootstrap/dist/css/bootstrap-theme.css 3:1-142
 @ ./src/main/js/css.js

ERROR in ./node_modules/file-loader/dist/cjs.js!./node_modules/extract-loader/lib/extractLoader.js!./node_modules/css-loader!./node_modules/bootstrap/dist/css/bootstrap.css
Module build failed: D:\blablabla\node_modules\bootstrap\dist\css\bootstrap.css:2
**exports = module.exports = require("../../../css-loader/lib/css-base.js")(false);(url)**

So, looks like it is required to handle both absolute and relative urls. At least I changed testing url to wider
**`/^[^!]*[\/\\]css-loader[\/\\].*\.js$/i.`**
and now application builds w/o errors.

Not sure how it should be fixed in proper way: via wider regexp or via relative-to-absolute conversion. I think rel2abs is more strict.

**Comment by rurikbor** [comment]
Forgot to add environment:
Windows10
node v6.11.2
webpack 3.10.0
extract-loader 1.0.2
css-loader v0.28.9

**Comment by benurb** [comment]
Hi @rurikbor 
Thanks for your detailed analysis. Yes, the relative paths seem to be a problem, which should be fixed by #30 .
I hope @jhnns finds time to review it in the next days, so he can push out a new release :)

**Comment by benurb** [comment]
This is fixed with v2.0.1 🎉 
Thank you for the report and sorry for the delay.
